CREATE TYPE "public"."comment_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('new_follower', 'new_comment', 'comment_like', 'post_like', 'post_featured', 'mention');--> statement-breakpoint
CREATE TYPE "public"."post_status" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
CREATE TYPE "public"."report_status" AS ENUM('pending', 'reviewed', 'resolved');--> statement-breakpoint
CREATE TYPE "public"."report_type" AS ENUM('spam', 'inappropriate', 'harassment', 'other');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'author', 'user');--> statement-breakpoint
CREATE TABLE "blog-app_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "blog-app_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"description" text,
	"color" varchar(7),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_category_name_unique" UNIQUE("name"),
	CONSTRAINT "blog-app_category_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog-app_comment_like" (
	"commentId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_comment_like_commentId_userId_pk" PRIMARY KEY("commentId","userId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"postId" integer NOT NULL,
	"authorId" varchar(255) NOT NULL,
	"parentId" integer,
	"status" "comment_status" DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "blog-app_email_preference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_email_preference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"newFollowers" boolean DEFAULT true NOT NULL,
	"newComments" boolean DEFAULT true NOT NULL,
	"postLikes" boolean DEFAULT true NOT NULL,
	"weeklyDigest" boolean DEFAULT true NOT NULL,
	"marketingEmails" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "blog-app_follower" (
	"followerId" varchar(255) NOT NULL,
	"followingId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_follower_followerId_followingId_pk" PRIMARY KEY("followerId","followingId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"type" "notification_type" NOT NULL,
	"title" varchar(255) NOT NULL,
	"message" text,
	"relatedUserId" varchar(255),
	"relatedPostId" integer,
	"relatedCommentId" integer,
	"isRead" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blog-app_post_bookmark" (
	"postId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_post_bookmark_postId_userId_pk" PRIMARY KEY("postId","userId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_post_like" (
	"postId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_post_like_postId_userId_pk" PRIMARY KEY("postId","userId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_post_series" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_post_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"authorId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "blog-app_post_series_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog-app_post_tag" (
	"postId" integer NOT NULL,
	"tagId" integer NOT NULL,
	CONSTRAINT "blog-app_post_tag_postId_tagId_pk" PRIMARY KEY("postId","tagId")
);
--> statement-breakpoint
CREATE TABLE "blog-app_post_view" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_post_view_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"postId" integer NOT NULL,
	"userId" varchar(255),
	"ipAddress" varchar(45),
	"userAgent" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blog-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"excerpt" text,
	"featuredImage" text,
	"readingTime" integer,
	"status" "post_status" DEFAULT 'draft' NOT NULL,
	"isFeatured" boolean DEFAULT false NOT NULL,
	"authorId" varchar(255) NOT NULL,
	"categoryId" integer,
	"seriesId" integer,
	"seriesOrder" integer,
	"publishedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "blog-app_post_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog-app_report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reporterId" varchar(255) NOT NULL,
	"reportedUserId" varchar(255),
	"reportedPostId" integer,
	"reportedCommentId" integer,
	"type" "report_type" NOT NULL,
	"reason" text NOT NULL,
	"status" "report_status" DEFAULT 'pending' NOT NULL,
	"reviewedBy" varchar(255),
	"reviewedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blog-app_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blog-app_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"slug" varchar(50) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "blog-app_tag_name_unique" UNIQUE("name"),
	CONSTRAINT "blog-app_tag_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "blog-app_user_social_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog-app_user_social_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"platform" varchar(50) NOT NULL,
	"url" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blog-app_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" text,
	"password" varchar(255),
	"clerkId" varchar(255),
	"username" varchar(50) NOT NULL,
	"displayName" varchar(100),
	"bio" text,
	"profileImage" text,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "blog-app_user_clerkId_unique" UNIQUE("clerkId"),
	CONSTRAINT "blog-app_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "blog-app_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "blog-app_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "blog-app_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "comment_post_id_idx" ON "blog-app_comment" USING btree ("postId");--> statement-breakpoint
CREATE INDEX "comment_author_id_idx" ON "blog-app_comment" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "comment_parent_id_idx" ON "blog-app_comment" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "comment_status_idx" ON "blog-app_comment" USING btree ("status");--> statement-breakpoint
CREATE INDEX "notification_user_id_idx" ON "blog-app_notification" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "notification_is_read_idx" ON "blog-app_notification" USING btree ("isRead");--> statement-breakpoint
CREATE INDEX "post_author_id_idx" ON "blog-app_post" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "post_status_idx" ON "blog-app_post" USING btree ("status");--> statement-breakpoint
CREATE INDEX "post_slug_idx" ON "blog-app_post" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "post_featured_idx" ON "blog-app_post" USING btree ("isFeatured");--> statement-breakpoint
CREATE INDEX "post_published_at_idx" ON "blog-app_post" USING btree ("publishedAt");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "blog-app_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_username_idx" ON "blog-app_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "blog-app_user" USING btree ("email");